runtime: nodejs10

handlers:
  - url: /
    static_files: frontend/build/index.html
    upload: frontend/build/index.html

  - url: /
    static_dir: frontend/build
  
  - url: /*
    secure: always
    redirect_http_response_code: 301
    script: auto

